FROM docker.io/library/caddy:2.11-builder@sha256:5fa9a318e2f32bf2c75f59eb4bad9b3e1b8522fbce9a689a6a7d4614145672f3 AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM docker.io/library/caddy:2.11@sha256:eaaddd7f0b17fcd97e61d7ad1d9dad5c541780094f4f4a2d5cb21d1ae265204c

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
